version: "3.8"
services:
  # Backing Services
  wetalk-mysql:
    image: "mysql:8.0"
    container_name: "wetalk-mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  wetalk-redis:
    image: "redis:7.0"
    container_name: "wetalk-redis"
    ports:
      - 6379:6379